services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "8082:80"
    depends_on:
      - backend
    networks:
      - docker-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - docker-network

  database:
    image: mongo:latest
    container_name: mongo-container
    volumes:
      - mongo-data:/data/db
    networks:
      - docker-network

volumes:
  mongo-data:

networks:
  docker-network:
    driver: bridge
